---

num_rounds: 40
num_clients: 4
local_epochs: 4  
batch_size: 4
num_classes: 2
num_clients_per_round_fit: 2
num_clients_per_round_eval: 2
device: 'cuda:0'

config_fit:
  lr: 0.0003
  momentum: 0.9
  weight_decay: 0.00001
  nesterov: false
  optimizer: 'Adam'
  loss: 'BCEWithLogitsLoss'

defaults:
  - strategy: fedavg
  - model: net
  - dataset: livseg
